# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# UPDATED: 
# vagrant-berkshelf was outdated.
# So you need to run `berks install --path cookbooks` first

Vagrant.configure("2") do |config|
  config.omnibus.chef_version = :latest
  config.vm.box = "opscode-centos-6.5"
  config.vm.box_url = "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.5_chef-provisionerless.box"
  config.vm.network :private_network, ip: "192.168.33.10"
  config.vm.provider :virtualbox do |vb|
    # Don't boot with headless mode
    vb.gui = true
 
    # Use VBoxManage to customize the VM. For example to change memory:
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = ["./cookbooks", "./site-cookbooks"]
    chef.add_recipe "mysql::default"
    chef.add_recipe "mysql::server"
    chef.add_recipe "php"
    chef.add_recipe "resolver"
    chef.add_recipe "iptables"
    chef.add_recipe "myapp"
    chef.json = {
      :mysql => {
        :server_root_password => "passwd",
        :server_repl_password => "passwd",
        :server_debian_password => "passwd"
      },
      :resolver => {
        :search => "localhost",
        :nameservers => ["8.8.8.8", "8.8.1.1"]
      }
    }
  end
end
