# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "CentOS-6.4-x86_64-ja"
  config.vm.box_url = "https://dl.dropboxusercontent.com/u/428597/vagrant_boxes/CentOS-6.4-x86_64-ja.box"
  config.vm.network :private_network, ip: "192.168.33.80"
  config.vm.hostname = 'chef-test01'

  ## Sample for using chef server
  config.vm.provision :chef_client do |chef|
    chef.chef_server_url = "https://chef.meguro.ryuzee.com"
    ## set username which is created at chef-server
    chef.validation_client_name = "chef-validator"
    ## set file path of secret key which is also created at chef-server.
    chef.validation_key_path = "#{ENV['HOME']}/.chef/chef-validator.pem"
    chef.client_key_path = "/etc/chef/client.pem"
    chef.environment ="development"
    chef.add_role "web"
    chef.add_recipe "analog"
  end
end
