# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = false 
  config.vm.define 'v' do |node|
    node.vm.box = "CentOS-6.4-x86_64-ja"
    node.vm.box_url = "https://dl.dropboxusercontent.com/u/428597/vagrant_boxes/CentOS-6.4-x86_64-ja.box"
    node.vm.hostname = 'v'
    node.vm.network :private_network, ip: "192.168.33.10"
    node.hostmanager.aliases = %w(v.ryuzee.com v2.ryuzee.com)
  end
end
