# -*- mode: ruby -*-
# vi: set ft=ruby :
require 'berkshelf/vagrant'

Vagrant.configure("2") do |config|
  config.vm.box = "CentOS-6.4-x86_64-ja"
  config.vm.box_url = "https://dl.dropboxusercontent.com/u/428597/vagrant_boxes/CentOS-6.4-x86_64-ja.box"
  config.vm.network :private_network, ip: "192.168.33.10"
  config.vm.provider :virtualbox do |vb|
    # Don't boot with headless mode
    vb.gui = true
 
    # Use VBoxManage to customize the VM. For example to change memory:
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end
  config.berkshelf.enabled = true

  config.vm.provision :chef_solo do |chef|
    chef.add_recipe "zabbix"
    chef.json = {
      :zabbix => {
        :agent => { 
          :servers => ["10.0.90.75"],
          :hostname => "vagrant-zabbix-sample",
          :install_method => "prebuild",
          :version => "2.0.0",
          :branch => "ZABBIX%20Latest%20Stable"
        }
      }
    }
  end
end
