# -*- mode: ruby -*-
# vi: set ft=ruby :
 
Vagrant.configure("2") do |config|
 
  # 共通設定
  box_name = "dummy"
  box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"
  ssh_username = "ec2-user"
 
  #---- ここからWebサーバ作る
  config.vm.define :web do |web|
    # EC2使う時も指定が必要なのでダミーを.
    web.vm.box = box_name
    web.vm.box_url = box_url
 
    web.vm.provider :aws do |aws, override|
      aws.access_key_id = ENV['AWS_ACCESS_KEY_ID']
      aws.secret_access_key = ENV['AWS_SECRET_KEY']
      aws.keypair_name = ENV['AWS_KEYPAIR_NAME']
      override.ssh.username = ssh_username
      override.ssh.private_key_path = ENV['AWS_PRIVATE_KEY_PATH']
 
      # タグを指定します
#aws.tags = ["test", "dev", "web"]
      # リージョンを設定します
      aws.region = "ap-northeast-1"
      # アベイラビリティゾーンを設定する必要がある場合
      aws.availability_zone = "ap-northeast-1c"
      # 標準のAmazonLinuxの場合。Chefを使うなら専用のAMIを使う 
      aws.ami = "ami-71b22570"
      # インスタンスタイプを設定します
      aws.instance_type = "t1.micro"
      aws.ssh_username = ssh_username 
      aws.security_groups = ["web"]
    end
 
    web.vm.provision :chef_client do |chef|
    chef.chef_server_url = "https://chef.meguro.ryuzee.com"
    chef.validation_client_name = "chef-validator"
    chef.validation_key_path = pathconv "#{ENV['HOME']}/.chef/chef-validator.pem"
    chef.client_key_path = pathconv "#{ENV['HOME']}/.chef/client.pem"
    chef.environment ="development"
    chef.add_role "web"
    chef.add_recipe "analog"
    end
  end
 
  #---- ここからDBサーバ作る
  config.vm.define :db do |db|
    # EC2使う時も指定が必要なのでダミーを.
    db.vm.box = box_name
    db.vm.box_url = box_url
    db.ssh.username = ssh_username
 
    db.vm.provider :aws do |aws, override|
      aws.access_key_id = ENV['AWS_ACCESS_KEY_ID']
      aws.secret_access_key = ENV['AWS_SECRET_KEY']
      aws.keypair_name = ENV['AWS_KEYPAIR_NAME']
      override.ssh.username = ssh_username
      override.ssh.private_key_path = ENV['AWS_PRIVATE_KEY_PATH']
 
      # タグを指定します
#      aws.tags = ["test", "dev", "db"]
      # リージョンを設定します
      aws.region = "ap-northeast-1"
      # アベイラビリティゾーンを設定する必要がある場合
      aws.availability_zone = "ap-northeast-1c"
      aws.ami = "ami-71b22570"
      # インスタンスタイプを設定します
      aws.instance_type = "t1.micro"
      aws.ssh_username = ssh_username 
      aws.security_groups = ["web"]
    end
 
    db.vm.provision :chef_client do |chef|
    chef.chef_server_url = "https://chef.meguro.ryuzee.com"
    chef.validation_client_name = "chef-validator"
    chef.validation_key_path = pathconv "#{ENV['HOME']}/.chef/chef-validator.pem"
    chef.client_key_path = pathconv "#{ENV['HOME']}/.chef/client.pem"
    chef.environment ="development"
    chef.add_role "web"
    chef.add_recipe "analog"
    end
  end
end

def pathconv(path)
  if(RUBY_PLATFORM.downcase =~ /mswin(?!ce)|mingw|cygwin|bccwin/)
    path = path.gsub('/', '\\')
  end
  path
end
