# -*- mode: ruby -*-
# vi: set ft=ruby :
require 'berkshelf/vagrant'

Vagrant.configure("2") do |config|

  # dummy box (required)
  config.vm.box = "dummy"
  config.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"

  config.vm.provider :aws do |aws, override|
    aws.access_key_id = ENV['AWS_ACCESS_KEY_ID']
    aws.secret_access_key = ENV['AWS_SECRET_ACCESS_KEY']

    region = "ap-northeast-1"
    aws.region = region 

    # Keypair
    env_key = region.upcase.gsub("-", "_")
    aws.keypair_name = ENV["AWS_KEYPAIR_NAME_#{env_key}"]
    override.ssh.private_key_path = ENV["AWS_PRIVATE_KEY_PATH_#{env_key}"]
    override.ssh.username = "ec2-user"

    aws.instance_type = "t1.micro"
    aws.ami = "ami-0d13700c"
    aws.availability_zone = "ap-northeast-1a"
    aws.security_groups = ["web"]
    aws.tags = { 'Name' => "vagrant", "env" => "dev" }

    # set user data
    aws.user_data = "#!/bin/sh\nsed -i 's/^.*requiretty/#Defaults requiretty/' /etc/sudoers\n"
  end

  config.omnibus.chef_version = :latest 
  config.berkshelf.enabled = true

  config.vm.provision :chef_solo do |chef|
    chef.run_list = [
      "recipe[apache2]"
    ]
  end
end
