# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "quantal64"
  config.vm.box_url = "http://bit.ly/vagrant-lxc-quantal64-2013-07-12"
  config.vm.network :private_network, ip: "192.168.33.10"
  config.vm.synced_folder "/tmp", "/vagrant_data"
end
