# -*- mode: ruby -*-
# vi: set ft=ruby :
require 'berkshelf/vagrant'

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.berkshelf.enabled = true
  config.omnibus.chef_version = :latest
  config.vm.box = "opscode-centos-6.4"
  # private_network の設定をしないと、ホスト側マシンからブラウザ等で繋がらないので注意
  #config.vm.network :private_network, ip: "192.168.33.10"
  config.vm.provision :chef_solo do |chef|
    chef.add_recipe "apache2"
  end
end
