site :opscode
cookbook 'apt'
cookbook 'yum'
cookbook 'rabbitmq'
cookbook 'redisio'
cookbook 'iptables'

cookbook 'sensu', git:"https://github.com/sensu/sensu-chef.git"

cookbook 'sensu-client-wrapper', path:"./sensu-client-wrapper"
cookbook 'sensu-server-wrapper', path:"./sensu-server-wrapper"
