site :opscode

cookbook 'yum', "~> 3.0.0"
cookbook 'erlang', "~> 1.4.2"
cookbook 'sensu', "~> 0.8.0", git:"https://github.com/sensu/sensu-chef.git"
cookbook 'sensu-client-wrapper', ">= 0.2.0", git:"https://github.com/ryuzee-cookbooks/sensu-client-wrapper.git"
cookbook 'sensu-server-wrapper', ">= 0.2.0", git:"https://github.com/ryuzee-cookbooks/sensu-server-wrapper.git"
cookbook 'ruby'
cookbook 'sensu-admin', git:"https://github.com/sensu/sensu-admin-chef.git"
cookbook 'graphite', git:"https://github.com/hw-cookbooks/graphite.git", tag: "v0.4.5"
