# -*- mode: ruby -*-
# vi: set ft=ruby :
require 'berkshelf/vagrant'

Vagrant.configure("2") do |config|
  config.berkshelf.enabled = true

  config.vm.define :server do |server|
    server.vm.box = "CentOS-6.4-x86_64-ja"
    server.vm.box_url = "https://dl.dropboxusercontent.com/u/428597/vagrant_boxes/CentOS-6.4-x86_64-ja.box"
    server.vm.network :private_network, ip: "192.168.33.10"
    server.vm.provider :virtualbox do |vb|
      # Don't boot with headless mode
      vb.gui = true
   
      # Use VBoxManage to customize the VM. For example to change memory:
      vb.customize ["modifyvm", :id, "--memory", "1024"]
    end

    server.vm.provision :chef_solo do |chef|
      chef.add_recipe "sensu::default"
      chef.add_recipe "sensu::rabbitmq"
      chef.add_recipe "sensu::redis"
      chef.add_recipe "sensu::api_service"
      chef.add_recipe "sensu::dashboard_service"
      chef.add_recipe "sensu::server_service"
      chef.json = {
        :sensu => {
            :use_ssl => false,
            :rabbitmq => {
              :host => "localhost",
              :port => 5672, 
              :user => "admin",
              :password => "password"
            },
            :redis => {
              :host => "localhost",
              :port => 6379
            },
            :api => {
              :host => "192.168.33.10",
              :bind => "0.0.0.0",
              :port => 9000
            },
            :dashboard => {
               :bind => '0.0.0.0',
               :port => 8080,
               :user => 'admin',
             :password => 'password'
            }
        }
      }
    end
  end
end
