VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "CentOS-6.4-x86_64-ja"
  config.vm.provision :shell, :inline => "sudo yum update -y" 
  config.vm.network :private_network, ip: "192.168.33.10"
  
  config.cache.auto_detect = false
  config.cache.enable :yum
end
