# -*- mode: ruby -*-
# vi: set ft=ruby :
 
# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"
 
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "vagrant-lxc-CentOS-6.4-x86_64-ja"
  config.vm.box_url = "https://dl.dropboxusercontent.com/u/428597/vagrant_boxes/vagrant-lxc-CentOS-6.4-x86_64-ja.box"
  config.vm.synced_folder "./", "/vagrant_data"
end
